CREATE TABLE IF NOT EXISTS founder_expenses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  spent_on TEXT NOT NULL,
  title TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('PREPARATION','EXPERIMENT','REGISTRATION','OFFICE','OTHER')),
  gross_paid_cents INTEGER NOT NULL CHECK (gross_paid_cents >= 0),
  refunded_cents INTEGER NOT NULL DEFAULT 0 CHECK (refunded_cents >= 0 AND refunded_cents <= gross_paid_cents),
  payment_method TEXT NOT NULL DEFAULT '',
  payee TEXT NOT NULL DEFAULT '',
  payment_reference TEXT NOT NULL DEFAULT '',
  refund_reference TEXT NOT NULL DEFAULT '',
  purpose TEXT NOT NULL DEFAULT '',
  outcome TEXT NOT NULL DEFAULT '',
  disposal TEXT NOT NULL DEFAULT '',
  business_relevance INTEGER NOT NULL DEFAULT 1 CHECK (business_relevance IN (0,1)),
  status TEXT NOT NULL DEFAULT 'PENDING_CONVERSION' CHECK (status IN ('PENDING_CONVERSION','COMPANY_CONFIRMED','PERSONAL','REIMBURSED')),
  decision_id INTEGER REFERENCES founder_decisions(id) ON DELETE SET NULL,
  evidence_note TEXT NOT NULL DEFAULT '',
  file_key TEXT NOT NULL DEFAULT '',
  file_name TEXT NOT NULL DEFAULT '',
  file_type TEXT NOT NULL DEFAULT '',
  file_size INTEGER NOT NULL DEFAULT 0,
  file_hash TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_founder_expenses_date ON founder_expenses(spent_on DESC, id DESC);
