const categories = ['PREPARATION', 'EXPERIMENT', 'REGISTRATION', 'OFFICE', 'OTHER'];
const statuses = ['PENDING_CONVERSION', 'COMPANY_CONFIRMED', 'PERSONAL', 'REIMBURSED'];
const filePattern = /^data:(image\/(?:jpeg|png|webp)|application\/pdf|application\/ofd|application\/xml|text\/xml);base64,([A-Za-z0-9+/=]+)$/;
const json = (body, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' } });
function text(body, key, max, required = false) { const value = body[key] ?? ''; if (typeof value !== 'string' || value.trim().length > max || (required && !value.trim())) throw new Error(`字段 ${key} 不能为空或超过长度限制`); return value.trim(); }
function date(body, key) { const value = text(body, key, 10, true); if (!/^\d{4}-\d{2}-\d{2}$/.test(value) || !Number.isFinite(Date.parse(value)) || new Date(value).toISOString().slice(0, 10) !== value) throw new Error(`${key} 日期不正确`); return value; }
function cents(body, key, optional = false) { const value = body[key]; if (optional && (value === undefined || value === '')) return 0; if (!Number.isSafeInteger(value) || value < 0 || value > 1e12) throw new Error(`${key} 金额不正确`); return value; }
async function storeFile(env, data, name) { if (!data) return null; if (!env.PROCUREMENT_FILES) throw new Error('文件存储未配置，请先配置 R2'); const match = String(data).match(filePattern); if (!match) throw new Error('凭证文件格式不支持'); const bytes = Uint8Array.from(atob(match[2]), c => c.charCodeAt(0)); if (bytes.length > 10 * 1024 * 1024) throw new Error('凭证文件不能超过10 MB'); const key = `founder/${new Date().toISOString().slice(0, 10)}/${crypto.randomUUID()}`; const hash = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', bytes)), b => b.toString(16).padStart(2, '0')).join(''); await env.PROCUREMENT_FILES.put(key, bytes, { httpMetadata: { contentType: match[1], contentDisposition: `inline; filename="${String(name || '凭证').replace(/[^\w.-]+/g, '_')}"` } }); return { key, type: match[1], size: bytes.length, hash }; }
function validate(body) { const gross = cents(body, 'gross_paid_cents'); const refunded = cents(body, 'refunded_cents', true); if (refunded > gross) throw new Error('退款金额不能超过原始付款金额'); const category = text(body, 'category', 30, true); if (!categories.includes(category)) throw new Error('支出类别不正确'); const status = text(body, 'status', 30, true); if (!statuses.includes(status)) throw new Error('支出状态不正确'); const decisionId = body.decision_id === '' || body.decision_id === null || body.decision_id === undefined ? null : Number(body.decision_id); if (decisionId !== null && (!Number.isSafeInteger(decisionId) || decisionId < 1)) throw new Error('关联决策不正确'); return [date(body, 'spent_on'), text(body, 'title', 160, true), category, gross, refunded, text(body, 'payment_method', 40), text(body, 'payee', 160), text(body, 'payment_reference', 160), text(body, 'refund_reference', 160), text(body, 'purpose', 1000), text(body, 'outcome', 1000), text(body, 'disposal', 1000), 1, status, decisionId, text(body, 'evidence_note', 2000)]; }
function decorate(row) { return row ? { ...row, net_amount_cents: Number(row.gross_paid_cents) - Number(row.refunded_cents), has_evidence: Boolean(row.file_key) } : row; }
export async function founderRecords({ request, env, id, file }) {
  if (!env.DB) return json({ error: 'D1 binding DB 未配置' }, 500);
  const method = request.method.toUpperCase();
  if (file) { if (method !== 'GET') return json({ error: '请求方法不支持' }, 405); const row = await env.DB.prepare('SELECT file_key, file_type FROM founder_expenses WHERE id = ?').bind(Number(id)).first(); if (!row?.file_key || !env.PROCUREMENT_FILES) return json({ error: '暂无凭证' }, 404); const object = await env.PROCUREMENT_FILES.get(row.file_key); if (!object) return json({ error: '凭证文件不存在' }, 404); return new Response(object.body, { headers: { 'Content-Type': object.httpMetadata?.contentType || row.file_type || 'application/octet-stream', 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff' } }); }
  const allowed = id ? ['GET', 'PATCH', 'DELETE'] : ['GET', 'POST']; if (!allowed.includes(method)) return json({ error: '请求方法不支持' }, 405); if (id && (!Number.isSafeInteger(Number(id)) || Number(id) < 1)) return json({ error: '记录编号不正确' }, 400);
  if (method === 'GET') { if (id) { const row = await env.DB.prepare('SELECT * FROM founder_expenses WHERE id = ?').bind(Number(id)).first(); return row ? json({ record: decorate(row) }) : json({ error: '记录不存在' }, 404); } const { results } = await env.DB.prepare('SELECT * FROM founder_expenses ORDER BY spent_on DESC, id DESC').all(); return json({ records: (results || []).map(decorate) }); }
  if (method === 'DELETE') { const result = await env.DB.prepare('DELETE FROM founder_expenses WHERE id = ?').bind(Number(id)).run(); return result.meta?.changes ? json({ success: true }) : json({ error: '记录不存在' }, 404); }
  let body, values; try { body = await request.json(); if (!body || typeof body !== 'object' || Array.isArray(body)) throw new Error('请求内容不正确'); values = validate(body); } catch (error) { return json({ error: error.message || '请求内容不正确' }, 400); }
  const columns = ['spent_on', 'title', 'category', 'gross_paid_cents', 'refunded_cents', 'payment_method', 'payee', 'payment_reference', 'refund_reference', 'purpose', 'outcome', 'disposal', 'business_relevance', 'status', 'decision_id', 'evidence_note'];
  let stored = null; try { stored = await storeFile(env, body.evidence_data, text(body, 'evidence_file_name', 200)); } catch (error) { return json({ error: error.message }, 400); }
  if (stored) { columns.push('file_key', 'file_name', 'file_type', 'file_size', 'file_hash'); values.push(stored.key, text(body, 'evidence_file_name', 200, true), stored.type, stored.size, stored.hash); }
  const statement = method === 'POST' ? env.DB.prepare(`INSERT INTO founder_expenses (${columns.join(', ')}) VALUES (${columns.map(() => '?').join(', ')})`).bind(...values) : env.DB.prepare(`UPDATE founder_expenses SET ${columns.map(column => `${column} = ?`).join(', ')}, updated_at = CURRENT_TIMESTAMP WHERE id = ?`).bind(...values, Number(id));
  const result = await statement.run(); if (method === 'PATCH' && !result.meta?.changes) return json({ error: '记录不存在' }, 404); return json({ success: true, id: id ? Number(id) : result.meta.last_row_id }, method === 'POST' ? 201 : 200);
}
